services:
  webhooksender:
    image: ghcr.io/eewbot/webhook-sender:v0.4.0
    hostname: webhooksender
    container_name: webhooksender__webhooksender
    restart: unless-stopped

    environment:
      SENDER_IPS: ${SENDER_IPS}
      RETRY_IPS: ${RETRY_IPS}
      LISTEN: ${LISTEN}
      AUTH_TOKEN: ${AUTH_TOKEN}

    command: /usr/bin/webhook-sender

    deploy:
      resources:
        limits:
          memory: 512m

    network_mode: host
